### ISSUE TITLE
Question: how does this relate to WebWorkers in Deno?

### ISSUE THREAD

**Issue by tmcw** [casual-simulation/node-deno-vm#28]
Hi! First off - thanks for writing this module, I've been working on something that uses it and it's been a godsend! I'm a newbie to Deno and only now discovered that it supports a WebWorker concept of its own - https://deno.land/manual@v1.30.0/runtime/workers

Which seems pretty interesting! Would love to know how you folks think about the tradeoffs - if one is already in a Deno environment, does it make sense to just use WebWorkers for the same kind of work as node-deno-vm? It seems like it provides some of the same benefits but with Isolate isolation rather than process isolation?

**Comment by KallynGowdy** [comment]
Hi @tmcw ! This project was actually designed as a sort of pseudo-implementation of [Web Workers](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API) for Node.js.
When I designed this project, I wanted to use Web Workers from inside Node.js that also had security controls so I could limit access to things like the file system. At the time, the best that Node.js had was [`vm2`](https://www.npmjs.com/package/vm2), and the security design of that tool simply wasn't something that I was comfortable with (Specifically with respect to denial of service and crash resilience). So, I decided it would be nice to have something similar to Web Workers except with the idea that it should use a separate process and also it should use Deno as the runtime (which has a much better sandbox design than Node.js).

As for how this library compares to the Web Worker support in Deno, I would say they compare pretty similarly. The major difference is that this library is designed to be used from Node.js, while Deno Workers are used from Deno.
Essentially, if you are already using Deno, then you should definitely try to see if the Web Workers in Deno support what you need. Otherwise if you are already using Node.js, you can use this library to give you Deno's security features through a Web Worker-like API.

Really the biggest thing to be careful about with in-process workers are the possibility of [Spectre-like](https://en.wikipedia.org/wiki/Spectre_(security_vulnerability)) side-channel attacks that separate processes are better at preventing.
On the other hand, Deno Web Workers are likely to be much quicker at communication with the main thread since they can use direct thread-to-thread communication and don't have a complicated marshalling step like this library does.

**Comment by tmcw** [comment]
Thanks! Months later this has been a super helpful response to get me started with this tricky problem area, and also we're back to trying out deno-vm because of issues with Deno Workers.
